trigger:
  branches:
    include:
    - main
variables:
- name: LT_USERNAME
  value: 'rahulkumarlambdatest'
- name: LT_ACCESS_KEY
  value: 'dboZK7so8koMnIR1tN11aKfMgxyKtDpb90IlyaCj4n6n7tQeK6'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Lambdatest.lambda-azure-pipeline-extention.configuration-task.configuration@1
      displayName: "LambdaTest configuration setup"
      inputs:
        connection: 'Service Account Project sesstings'
        isTunnelActivate: true
      env:
        LT_BUILD_NAME: Test_Sample_Playwright
    - task: CmdLine@2
      displayName: "Command Line Script"
      inputs:
        script: |
          npm install
          node playwright-single.js
    - task: Lambdatest.lambda-azure-pipeline-extention.showResults-task.LambdatestResults@1
      displayName: "Lambdatest Results"
      env:
        LT_BUILD_NAME: Test_Sample_Playwright

